
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-21T13:46:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce41b61b6570490949bd12b514e9f6de46d19c1f",
 "version": "0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
